---
title: "Hacklab Developer Census 2020"
description: "Preliminary Draft - `r Sys.Date()`"
output: 
  html_document:  
    # instead of distill::distill_article:
    toc: true
    toc_float: true # not working in distill...
    toc_depth: 2
    toc_collapsed: true
    # theme: paper
    css: css_theme/css_from_scratch.css # css instead of theme
---




```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE) # we do not want to display the code

# Environment:

library(xaringanExtra) # to be able to have tabs. To install: install 'devtools' package, then run: devtools::install_github("gadenbuie/xaringanExtra")
xaringanExtra::use_panelset() # allow the creation of tabs in Distill (see https://github.com/rstudio/distill/issues/11)

library(tidyverse) # includes dplyr, tidyr, ggplot2, rio, stringr, ...

library(leaflet) # for the interactive map
library(tmaptools) # for geocoding

library(wordcloud) # for the wordcloud at Q33

library(tidyr) # for Q30 and Q31

library(plotly) # for interactive bubble plots

library(ggiraph)
```

```{r}

# Data:

Qs <- rio::import("data/clean/clean_all_Qs.rds") %>%
  # reodering certain factors for the plots: (use barplot_ordered() for plotting)
  mutate(
    purch_influence_16 = fct_relevel(purch_influence_16,
                                     "I have little or no influence",
                                     "I have some influence",
                                     "I have a great deal of influence"
    ),    
    job_satisfaction_22 = fct_relevel(job_satisfaction_22,
                                      "Very dissatisfied",
                                      "Slightly dissatisfied",
                                      "Neither satisfied nor dissatisfied",
                                      "Slightly satisfied",
                                      "Very satisfied"),
    edu_importance_20 = fct_relevel(edu_importance_20,
                                    "Not at all important/not necessary",
                                    "Somewhat important",
                                    "Fairly important",
                                    "Very important",
                                    "Critically important"),
    company_size_23 = fct_relevel(company_size_23,
                                  "Over 500",
                                  "Over 100",
                                  "Below 100",
                                  "Below 20",
                                  "Below 10",
                                  "1"),
    overtime_work_25 = fct_relevel(overtime_work_25,
                                   "Often: 1-2 days per week",
                                   "Frequently: 3 or more days per week",
                                   "Sometimes: 1-2 days per month but less than weekly",
                                   "Occasionally: 1-2 days per quarter but less than monthly",
                                   "Rarely: 1-2 days per year or less",
                                   "Never"),
    monthly_salary_28 = fct_relevel(monthly_salary_28,
                                    "Greater than GHS 25,000",
                                    "GHS 20,000 - GHS 25,000",
                                    "GHS 15,000 - GHS 20,000",
                                    "GHS 10,000 - GHS 15,000",
                                    "GHS 8,000 - GHS 10,000",
                                    "GHS 6,000 - GHS 8,000",
                                    "GHS 5,000 - GHS 6,000",
                                    "GHS 4,000 - GHS 5,000",
                                    "GHS 3,500 - GHS 4,000",
                                    "GHS 3,000 - GHS 3,500",
                                    "GHS 2,500 - GHS 3,000",
                                    "GHS 2,000 - GHS 2,500",
                                    "GHS 1,500 - GHS 2,000",
                                    "Less than GHS 1,500"),
    prim_study_19 = recode(prim_study_19, 
                           "Computer_Science_Engineering" = "Computer Science/Engineering",
                           "Information_Technology" = "Information Technology",
                           "Other_Engineering" = "Other Engineering",
                           "Health_Science" = "Health Science",
                           "Social_Science" = "Social Science",
                           "Web_Development_Web_Design" = "Web-Development/Web-Design",
                           "General_Science" = "General Science",
                           "Electrical_Engineering" = "Electrical Engineering",
                           "Visual_Arts" = "Visual Arts",
                           "Agricultural_Science" = "Agricultural Science",
                           "Graphic_Design" = "Graphic Design",
                           "General_Arts" = "General Arts",
                           "Mathematics_Statistics" = "Mathematics/Statistics"),
    prim_study_19 = fct_relevel(prim_study_19,
                                "Education",
                                "Social Science",
                                "Graphic Design",
                                "Architecture",
                                "Visual Arts",
                                "Business",
                                "General Arts",
                                "General Science",
                                "Health Science",
                                "Chemistry",
                                "Other Engineering",
                                "Physics",
                                "Agricultural Science",
                                "Web-Development/Web-Design",
                                "Mathematics/Statistics",
                                "Electrical Engineering",
                                "Information Technology",
                                "Computer Science/Engineering"),   
    highest_edu_18 = recode(highest_edu_18, 
                            "Secondary_High_School" = "Secondary High School",
                            "Basic_Education" = "Basic Education",
                            "Higher_National_Diploma" = "Higher National Diploma",
                            "Professional_Diploma" = "Professional Diploma",
                            "Teacher_Diploma" = "Teacher Diploma",
                            "College" = "Bachelor"),
    highest_edu_18 = fct_relevel(highest_edu_18,
                                 "Basic Education",
                                 "Secondary High School",
                                 "Teacher Diploma",
                                 "Professional Diploma",
                                 "Higher National Diploma",
                                 "Bachelor",
                                 "Master")
  )

skills <- rio::import("data/clean/skills_final.csv") %>% 
  select(-V1) %>%  # artifact due to a save as .csv to remove (at least on a Mac?)
  mutate_all(na_if,"") # the column 'level' contains blanks ("") instead of NAs -> transform them to NAs.
# we add characteristics of the respondents to the skills, 
# so that we can differentiate their popularity by occupation or gender:
skills_with_characteristics <- skills %>% left_join(select(Qs, ID, profession_1, gender_35), by = c("id" = "ID"))
 
number_of_respondents = dim(Qs)[1] # number of respondents (272) used to compute percentages.
number_of_prof_dev = dim(Qs %>% filter(profession_1 == "I am a developer by profession"))[1]
number_of_students = dim(Qs %>% filter(profession_1 == "I am a student who is learning to code"))[1]


```

```{r}

# Themes and Functions:

HL_colors = c("#610b70","#88b101","#eb1c96","#e98403","#454545")
HL_font = "sans" # !!! Should change and use Gotham !!!
main_fontsize = 7 

barplot_theme <- function(){
  # the definition of a custom ggplot theme for our barplots.
  theme_minimal() + 
    theme(
      plot.title = element_text(family = HL_font, size = main_fontsize + 2, color = "black"),
      # plot.subtitle = element_text(family = HL_font, size = main_fontsize),
      axis.title = element_text(family = HL_font, size = main_fontsize, color = "black"),
      axis.text = element_text(family = HL_font, size = main_fontsize, color = "black"),
      # plot.caption = element_text(hjust = 0, family = my_font, 
      #                             size = main_fontsize, face= "italic"), #Default is hjust=1 / 0
      plot.title.position = "plot",  # left-align title
      # plot.caption.position =  "plot", 
      panel.grid.minor.x = element_blank(),  # remove useless minor grid
      panel.grid.major.y = element_blank(),  # remove useless major grid in bar charts
      panel.grid.major.x = element_blank(),  # remove useless major grid in bar charts
      axis.title.x = element_blank(), # we do not want an y axis for the barplot, we have labels already
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank()
      # plot.margin = margin(0.1, 0.1, 0.1, 0.1, unit = "cm")
    )
}

basic_barplot <- function(my_df, a_factor, its_values, labels, title){
  # a function to plot a standard barplot
  # uses the barplot_theme defined above
  # needs an (ordered) factor as input, and its values
  # returns a ggplot
  current_plot <- ggplot(data = my_df, 
                         aes(x = fct_reorder({{a_factor}}, {{its_values}}), 
                             y = {{its_values}})) + 
    geom_col(fill = HL_colors[1]) + 
    geom_text(
      aes(label = {{labels}}, y = {{its_values}} + (0.06*max({{its_values}}))),
      size = 2
    ) +
    scale_y_continuous(labels = scales::percent) +
    barplot_theme() + 
    coord_flip() +
    labs(title = stringr::str_wrap(title,100)) + # automated text wrap in title
    xlab("") +
    ylab("")
  return(current_plot)
}

#Function for barplot that does not override order
barplot_ordered <- function(my_df, a_factor, its_values, labels, title){
  # a function to plot a standard barplot
  # uses the barplot_theme defined above
  # needs an (ordered) factor as input, and its values
  # returns a ggplot
  current_plot <- ggplot(data = my_df, 
                         aes(x = {{a_factor}},
                             y = {{its_values}})) + 
    geom_col(fill = HL_colors[1]) + 
    geom_text(
      aes(label = {{labels}}, y = {{its_values}} + (0.06*max({{its_values}}))),
      size = 2
    ) +
    scale_y_continuous(labels = scales::percent) +
    barplot_theme() + 
    coord_flip() +
    labs(title = stringr::str_wrap(title,100)) + # automated text wrap in title
    xlab("") +
    ylab("")
  return(current_plot)
}

compute_perc <- function(my_df, a_factor){
  # a small function to count a factor and compute the percentages
  # also return the percentages as char for labelling.
  # USE THIS FUNCTION IF THE SUM OF THE ANSWERS IS 272! (including NAs) -> not working if several possible choices.
  my_df %>%
    count({{a_factor}}) %>%
    drop_na() %>% # always in percentage of the respondents to the question.
    mutate(
      perc = n/sum(n),
      perc_label = paste0(as.character(round(perc*100,1)), "%")
    ) %>% return()
  
}

compute_perc_popular_skills <- function(the_skills, skillset, number_of_resp){
  # USE THIS FUNCTION for the popular skills (last year + both)
  # NOTE: we use all respondents, not only those who responded. -> some respondents did not enter any skills. -> not optimal, but annoying to correct?
  the_skills %>%
    filter(tool %in% skillset) %>% # select only the languages from all the tools
    filter(level == "Worked with in PAST year" | level == "Both") %>%
    count(tool) %>%
    mutate(
      perc = n/number_of_resp, 
      perc_label = paste0(as.character(round(perc*100,1)), "%")
    ) %>% 
    arrange(-perc) %>%  
    return()
}

compute_perc_future_skills <- function(the_skills, skillset, number_of_resp){
  # USE THIS FUNCTION for the future, nexy year, skills (next year + both)
  # NOTE: we use all respondents, not only those who responded. -> some respondents did not enter any skills. -> not optimal, but annoying to correct?
  the_skills %>%
    filter(tool %in% skillset) %>% # select only the languages from all the tools
    filter(level == "Want to work with NEXT year" | level == "Both") %>%
    count(tool) %>%
    mutate(
      perc = n/number_of_resp, 
      perc_label = paste0(as.character(round(perc*100,1)), "%")
    ) %>% 
    arrange(-perc) %>%  
    return()
}

barplot_theme <- function(){
  # the definition of a custom ggplot theme for our barplots.
  theme_minimal() + 
    theme(
      plot.title = element_text(family = HL_font, size = main_fontsize + 2, color = "black"),
      # plot.subtitle = element_text(family = HL_font, size = main_fontsize),
      axis.title = element_text(family = HL_font, size = main_fontsize, color = "black"),
      axis.text = element_text(family = HL_font, size = main_fontsize, color = "black"),
      # plot.caption = element_text(hjust = 0, family = my_font, 
      #                             size = main_fontsize, face= "italic"), #Default is hjust=1 / 0
      plot.title.position = "plot",  # left-align title
      # plot.caption.position =  "plot", 
      panel.grid.minor.x = element_blank(),  # remove useless minor grid
      panel.grid.major.y = element_blank(),  # remove useless major grid in bar charts
      panel.grid.major.x = element_blank(),  # remove useless major grid in bar charts
      axis.title.x = element_blank(), # we do not want an y axis for the barplot, we have labels already
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank()
      # plot.margin = margin(0.1, 0.1, 0.1, 0.1, unit = "cm")
    )
}
 
bubble_plotly_theme <- function(){
  theme_minimal() +
  theme(legend.position="none",
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank()
        )
}

colours = c( "#610b70", "#88b101", "#eb1c96", "#e98403", "#45454C", "#000001",  "black")

bubble_plot <- function(df, x_value, y_value, freq, colour_choice, title){
  ggplot(data = df, aes(x={{x_value}}, y={{y_value}}, 
              text = text)) + # text = text that appears when hover over the bubble, needs to be defined beforehand
  geom_point(aes(size=ifelse({{freq}}==0, NA, {{freq}}),  # bubbles with the size according to how many respondents
                 fill = {{x_value}}), # bubble color according to x value level
             alpha = 0.75, 
             shape = 19, color=NA) + # circles and no border
  scale_size(range = c(1.4, 15)) + # size of the bubbles
  labs( x= "", y = "", size = "Number of respondents", fill = "") +
  scale_fill_manual(values = {{colour_choice}}) +
  scale_colour_manual(values= "white")
    
}
```
Hello

## Relationship between job satisfaction and overtime work

Interestingly, people who work more than 3 times a week overtime are satisfied with their job. There seems no relationship that the more overtime the less job satisfaction. The tendency is rather the opposite. 

```{r, fig.align='center', out.width = '100%', fig.height=3}

# Bubble chart: Relationship between job satisfaction and overtime work
runningcounts.df <- as.data.frame(table(Qs$job_satisfaction_22, Qs$overtime_work_25))

relation_ordinal_Q22_25 <- runningcounts.df %>% rename(overtime_work_25 = Var2,
                                               job_satisfaction_22 = Var1) %>%
  mutate(overtime_work_25 = recode(overtime_work_25,
                                                "Often: 1-2 days per week" = "1-2 days per week",
                                                "Sometimes: 1-2 days per month but less than weekly" = "1-2 days per month",
                                      "Rarely: 1-2 days per year or less" = "<1-2 days per year",
                                   "Occasionally: 1-2 days per quarter but less than monthly" = "1-2 days per quarter",
                                   "Frequently: 3 or more days per week" = ">3 days per week"))

levels(relation_ordinal_Q22_25$overtime_work_25) <- gsub(" ", "\n", levels(relation_ordinal_Q22_25$overtime_work_25))
levels(relation_ordinal_Q22_25$job_satisfaction_22) <- gsub(" ", "\n", levels(relation_ordinal_Q22_25$job_satisfaction_22))

colours = c( "#610b70", "#88b101", "#eb1c96", "#e98403", "#45454C", "#000001")

relation_ordinal_Q22_25 <- relation_ordinal_Q22_25 %>%
  # prepare text for tooltip
  mutate(text = paste(Freq, "respondent/s"))

bubble_Q22_25<-bubble_plot(df = relation_ordinal_Q22_25, x_value = overtime_work_25, y_value = job_satisfaction_22, freq = Freq, colour_choice = colours, title = "") + bubble_plotly_theme()

ggplotly(bubble_Q22_25, width = 800, height = 600)
```

```{r, fig.align='center', out.width = '100%', fig.height=3}

# p <- barplot_ordered(my_df = compute_perc(Qs, age_range_6), 
#                 a_factor = age_range_6, its_values = perc, labels = perc_label, 
#                 tooltip = perc_label, data_id = perc,
#                 title = "") + scale_x_discrete(limits=rev)


bubble_Q22_25_resp <- ggplot(data = relation_ordinal_Q22_25, aes(x = overtime_work_25, y=job_satisfaction_22, 
              tooltip = "text")) + # text = text that appears when hover over the bubble, needs to be defined beforehand
  geom_point(aes(size=ifelse(Freq==0, NA, Freq),  # bubbles with the size according to how many respondents
                 fill = overtime_work_25), # bubble color according to x value level
             alpha = 0.75, 
             shape = 19, color=NA) + # circles and no border
  scale_size(range = c(1.4, 15)) + # size of the bubbles
  labs( x= "", y = "", size = "Number of respondents", fill = "") +
  scale_fill_manual(values = colours) +
  scale_colour_manual(values= "white") + bubble_plotly_theme()

bubble_Q22_25_resp <- ggplot(data = relation_ordinal_Q22_25, 
                             aes(x = overtime_work_25, 
                                 y=job_satisfaction_22, 
                                 tooltip = "text")) + # text = text that appears when hover over the bubble, needs to be defined beforehand
  geom_point_interactive(aes(size=ifelse(Freq==0, NA, Freq),
                             tooltip = text,
                             fill = overtime_work_25), # bubble color according to x value level
             alpha = 0.75, 
             shape = 19, 
             color=NA) + # circles and no border
  scale_size(range = c(1.4, 15)) + # size of the bubbles
  labs( x= "", y = "", size = "Number of respondents", fill = "") +
  scale_fill_manual(values = colours) +
  scale_colour_manual(values= "white") 


bubble_Q22_25_resp = ggplot(data = relation_ordinal_Q22_25) +
    geom_point_interactive(aes(x = overtime_work_25, 
                               y = job_satisfaction_22, 
                               color = overtime_work_25,
                               tooltip = text, 
                               size = Freq),
                           shape = 19) + 
scale_fill_manual(values = colours) +
  labs(x = "", y = "") +
    bubble_plotly_theme()


girafe(ggobj = bubble_Q22_25_resp, 
       fonts = list(sans = "Arial"),
       width_svg = 4.5, 
       height_svg = 4.5,
       options = list(
         opts_tooltip(use_fill = TRUE)))


```

